### ISSUE TITLE
GPA module

### ISSUE THREAD

**Issue by liwei1101** [J911/Coarse-to-Fine-Domain-Adaptation#1]
Hello!

Thank you for your wonderful work!

I'm more interested in the GPA module!

When will the code be made public?

**Comment by J911** [comment]
Hi,

First, this repository is not an official repository.
I reimplemented GPA Module developed myself, and it is incomplete. If I complete that, I will share it with you.

Thank you.

**Comment by liwei1101** [comment]
So that's it. 
Thanks~
